# Generated by Django 5.0.6 on 2024-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image_url',
            field=models.CharField(blank=True, default='https://i.ibb.co/VYqJN69/image-placeholder-icon-11.png', max_length=250, null=True),
        ),
    ]
