# Generated by Django 5.0.6 on 2024-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_friendrequest_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit ame consectetur adipisicing elit. Quos eaque aliquam exceptur sed vitae. Nisi?', max_length=105, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='Address', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_no',
            field=models.CharField(blank=True, default='Phone  ', max_length=12, null=True),
        ),
    ]
